spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://liquibase-dev.cxzsujcgmuzs.ap-northeast-1.rds.amazonaws.com:3306/demo?autoReconnect=true&useSSL=false
    username: "admin"
    password: "adminrds"