apiVersion: v1
kind: Namespace
metadata:
  name: liquibase   ## name of the namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: liquibase
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: liquibase-base
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80

# apiVersion: batch/v1
# kind: Job
# metadata:
#   namespace: liquibase
#   name: liquibase-job
# spec:
#   template:
#     spec:
#       containers:
#         - name: liquibase-base
#           image: CONTAINER_IMAGE
#       restartPolicy: Never
#   backoffLimit: 4
