apiVersion: v1
kind: Namespace
metadata:
  name: liquibase   ## name of the namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks-liquibase-my-app
  namespace: liquibase
  labels:
    app: aws-eks-liquibase-my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-eks-liquibase-my-app
  template:
    metadata:
      labels:
        app: aws-eks-liquibase-my-app
    spec:
      initContainers:
        - name: liquibase-base
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "testing"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: liquibase-database
                key: username
                optional: false
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: liquibase-database
                key: password
                optional: false
      containers:
        - name: aws-eks-liquibase-my-app
          image: 405081423162.dkr.ecr.ap-northeast-1.amazonaws.com/aws-eks-liquibase-my-app:latest
          ports:
          - containerPort: 80
