apiVersion: v1
kind: Namespace
metadata:
  name: liquibase   ## name of the namespace

---

apiVersion: batch/v1
kind: Job
metadata:
  namespace: liquibase
  name: aws-eks-liquibase-my-job
spec:
  template:
    spec:
      containers:
        - name: liquibase-base
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "testing"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: liquibase-database
                key: username
                optional: false
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: liquibase-database
                key: password
                optional: false
      restartPolicy: Never
  backoffLimit: 4
